const informations =
{ 1: { titre: "Lucas", texte: "Un grand coeur dans une carrure imposante, vous pourrez le reconnaître facilement par son amour pour les pommes et son tatouage sur l'avant-bras. Gardez vos distances avant qu'il vous fasse de gros câlins à mort." }, 
2: { titre: "Nolan", texte: "Ne vous approchez pas trop près, cette créature à la taille semblable aux Ogryns pourrait vous fouetter d'un seul coup de sa longue crinière qu'il aborde fièrement sur le crâne. Ne faites pas attention à son rasage, ça reste la faction des Numérique." }, 
3: { titre: "Lola", texte: "Régnant sur la faction des Numérique d'une main de fer (au secours aidez-nous svp), elle se distingue par ses tenues classes, cheveux mi-longs, lunettes et jambe cassée. Demandez-lui une photo et elle se fera un plaisir d'agrémenter votre galerie par sa grimace magistrale." }, 
4: { titre: "Lucy", texte: "Attention à ne pas brusquer notre nouvelle nouvelle recrue, je pense que vous verrez qui vous n'avez pas encore photographié..." },
5: { titre: "Nattéo", texte: "Méfiez-vous de cette créature et de sa carrure de Space Marine, il pourrait vous briser la main rien qu'en la serrant. Demandez-lui gentiment avant de prendre sa photo, au risque d'une mort douloureuse sinon. Vous pouvez le distinguer des autres par sa coupe de cheveux pratiquement rasée sur les côtés, et son bouc cachant son menton de Garde impérial." }, 
6: { titre: "Jennifer", texte: "Attention à ne pas brusquer notre nouvelle recrue, demandez-lui gentiment de l'ajouter dans votre bestiaire d'étudiants à chasser l'année prochaine. Peau mate, lunettes, bijoux d'or scintillant et cheveux impossibles à ignorer." }, 
7: { titre: "Inès", texte: "Ne vous faites pas aveugler par sa chevelure dorée, elle pourrait vous assassiner d'une seule traite en se faufilant derrière vous grâce à sa taille de Squat. Avant de la prendre en photo, remettez le contexte en évidence avant qu'elle n'hésite pendant 20 minutes pour finalement accepter. (Elle est très gentille mais légèrement timide)" }, 
8: { titre: "Ewan", texte: "Un véritable cultiste du Chaos enfoui derrière un corps de morfale sous stéroïdes. Je n'aurais pas d'autre indice à vous donner, mais si vous tentez d'appeler un certain Evan ou Ethan, il se reconnaîtra." }, 
9: { titre: "Cheick-Tahirou", texte: "Peau mate et dreadlocks en évidence, je n'aurais pas d'autre indice à vous communiquer pour cette créature. Vous pouvez attirer son attention en critiquant League of Legends si vous souhaitez faire mauvaise impression, ou simplement lui demander une photo pour l'ajouter à votre collection." }, 
10: { titre: "Aymeric", texte: "Cette créature se distingue par sa crinière affublée d'un bandeau noir et d'une moustache pimpante. Chers Krooks, portez votre attention sur ses mains, elles sont remplies d'anneaux de métal renfermant de mystérieux pouvoirs. Prenez garde à cette fouine et sa petite taille !" } };

function openInfo(numero) { const info = informations[numero]; document.getElementById("infoTitle").textContent = info.titre; document.getElementById("infoText").textContent = info.texte; document.getElementById("infoOverlay").style.display = "flex"; } /* ========================= FERMER L'INFO-BULLE ========================= */ function closeInfo() { document.getElementById("infoOverlay").style.display = "none"; } document.addEventListener("keydown", function(event) { if (event.key === "Escape") { closeInfo(); } });